# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(Build.SourcesDirectory)\SfHelloWorldApi\SfHelloWorldApi\SfHelloWorldApi.sfproj'
    msbuildArgs: '/t:Package /p:PackageLocation=$(Build.BinariesDirectory)\Release\Applications\SfHelloWorldApi\Pkg\release'
    platform: 'x64'
    configuration: '$(buildConfiguration)'

# Publish SF App Package to the Pipeline
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)\Release'
    ArtifactName: 'SfHelloWorldApi_dev'
    publishLocation: 'Container'